### ISSUE TITLE
How to Uglify?

### ISSUE THREAD

**Issue by Findiglay** [mauricedb/gulp-main-bower-files#1]
Hi,

Thanks for this, its a time saver!

Are there options to uglify? I tried to use gulp-uglify with this but its throwing an error.

Cheers,

**Comment by mauricedb** [comment]
You should be able to pipe the output straight into gulp-babel.

The following works just fine for me and produces minified output.

```javascript
var gulp = require('gulp');
var gulpMainBowerFiles = require('../index');
var uglify = require('gulp-uglify');

gulp.task('uglify', function(){
    return gulp.src('./bower.json')
        .pipe(gulpMainBowerFiles( ))
        .pipe(uglify())
        .pipe(gulp.dest('wwwroot/libs'));
});
```

**Comment by Findiglay** [comment]
@mauricedb still getting this error when I add uglify(). Tested uglify() with other non-bower scripts and is working fine.events.js:85

      throw er; // Unhandled 'error' event
            ^
    Error
       at new JS_Parse_Error (...\app\node_modules\gulp-   uglify\node_modules\uglify-js\lib\parse.js:196:18)
       at js_error (...\app\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:204:11)
       at parse_error (...\app\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:314:55)
       at Object.next_token [as input] (...\app\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:562:9)
       at next (...\app\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:661:25)
       at semicolon (...\app\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:708:30)
       at simple_statement (....\app\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:889:73)
       at ...\app\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:774:24
       at ...\app\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:722:24
       at ...\app\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:1469:23

This is my task: 

gulp.task('bower', function() {
  return gulp.src('./bower.json')
    .pipe(mainBowerFiles())
    .pipe(concat('vendor.js'))
    .pipe(uglify())
    .pipe(gulp.dest('client/assets/scripts'))
    .pipe(notify({ message: 'Bower task complete' }));
});

On Windows, using latest versions of both gulp-uglify and gulp-main-bower-files. Works fine without the .pipe(uglify())

**Comment by mauricedb** [comment]
@Findiglay Can you please share the content of your bower.json? It might be related to one of the packages listed in there.

**Comment by Findiglay** [comment]
{
       "name": "vets-to-do",
       "version": "0.0.1",
       "dependencies": {
        "angular": "1.3.16",
        "es5-shim": "~3.0.1",
        "jquery": "~1.11.0",
        "angular-resource": "1.3.16*",
        "angular-cookies": "1.3.16",
        "angular-sanitize": "1.3.16",
        "lodash": "~2.4.1",
        "angular-socket-io": "~0.6.0",
        "angular-ui-router": "~0.2.10",
        "bootstrap-select": "~1.7.2",
        "angular-bootstrap-select": "0.1.0-rc2",
        "angular-bootstrap-datetimepicker": "~0.3.12"
      },
      "devDependencies": {
         "bootstrap-sass": "~3.3.4"
      }
   }

Many thanks,

**Comment by mauricedb** [comment]
@Findiglay The error you are seeing is because some of the bower packages have main files that are CSS and LESS and not just JavaScript. Trying to run uglify on the CSS actually causes the error. Feel free to remove the debug() calls, they are only there to show which files are being processed.

```JavaScript
var gulp = require('gulp');
var mainBowerFiles = require('gulp-main-bower-files');
var concat = require('gulp-concat');
var uglify = require('gulp-uglify');
var notify = require('gulp-notify');
var debug = require('gulp-debug');
var gulpFilter = require('gulp-filter');

gulp.task('bower', function() {
    var filter = gulpFilter('**/*.js');
    return gulp.src('./bower.json')
        .pipe(mainBowerFiles())
        .pipe(filter)
        .pipe(debug())
        .pipe(concat('vendor.js'))
        .pipe(uglify())
        .pipe(filter.restore())
        .pipe(debug())
        .pipe(gulp.dest('client/assets/scripts'))
        .pipe(notify({ message: 'Bower task complete' }));
});
```

**Comment by Findiglay** [comment]
@mauricedb Understood, many thanks!
