### ISSUE TITLE
Extract css files separately?

### ISSUE THREAD

**Issue by a-am** [mauricedb/gulp-main-bower-files#2]
Is it possible with this plugin to extract js and css separately? Currently this is what I have to extract the js files: ```return gulp.src('./bower.json').pipe(plugins.mainBowerFiles( )).pipe(plugins.concat('bower.js')).pipe(gulp.dest('assets/js/src'));```

**Comment by millette** [comment]
I just started using it, copying from the [last example](https://github.com/mauricedb/gulp-main-bower-files#using-the-gulp-pipeline-to-use-bootstrap-with-jquery-and-minify-the-resulting-javascript) which uses gulp-filter to pick JavaScript files, if I understand correctly. It's also defining (overrides) which files to include.

You could define two similar tasks, one specific to css, the other for the JavaScript.

**Comment by mauricedb** [comment]
Yes using gulp-filter is the way to go. You can first filter for JS, reset
the filter and then filter for CSS in one task if you want to use a single
gulp task.

Maurice
Op 25 jul. 2015 03:10 schreef "Robin Millette" <notifications@github.com>:
