### ISSUE TITLE
Working example for concat bower files.

### ISSUE THREAD

**Issue by mitorski** [mauricedb/gulp-main-bower-files#24]
Hello there,

i looking for working example or explain how can i create task for concat and uglify all bower files in this case.

```
gulp.task('index-build', () => {
  let files = gulp.src([
    `${directories.build}/app.min.*.js`,
    `${directories.build}/constants.*.js`,
    `${directories.build}/templates.min.*.js`,
    `${directories.build}/styles.min.*.css`
  ]);
  return gulp
    .src(`${directories.sources}/index.html`)
    .pipe(pre({NODE_ENV: process.env.NODE_ENV}))
    .pipe( inject(
      gulp.src(`${directories.build}/**/*.sass`)
    ) )
    .pipe( inject(
      gulp.src(bower()) , { name: 'bower' }
    ) )
    .pipe( inject( files ,  { name: 'app' } )  )
    .pipe( gulp.dest( directories.build ) );
} );
```

Any tips?

Greeting

**Comment by mauricedb** [comment]
I might be missing something but I am not seeing any reference to gulp-main-bower-files here. Where is the issue with gulp-main-bower-files you are trying to solve?

**Comment by mitorski** [comment]
Is it -> import bower        from 'main-bower-files';

`.pipe( inject(
      gulp.src(bower()) , { name: 'bower' }
    ) )`

**Comment by mauricedb** [comment]
That is **main-bower-files** not **gulp-main-bower-files**. That Github repository is located [here](https://github.com/ck86/main-bower-files)

**Comment by mitorski** [comment]
Hm, this make a sense... thanks :D
