### ISSUE TITLE
Can this be used with gulp-add-src?

### ISSUE THREAD

**Issue by mcblum** [mauricedb/gulp-main-bower-files#34]
We have some dependencies in Bower, some in NPM. For some reason the following isn't working:

```
gulp.task('vendor', function () {

    // define our filters
    var jsFilter = gulpFilter(['**/*.js'], {
        restore: true
    });
    var cssFilter = gulpFilter(['**/*.css'], {
        restore: true
    });

    return gulp.src(mainBowerFiles({
        paths: {
            bowerDirectory: src.bower + 'bower_components',
            bowerJson: src.bower + 'bower.json'
        }
    }))
        .pipe(jsFilter)
        .pipe(addsrc([
            './node_modules/hoshi/dist/hoshi.js',
            './node_modules/angular-gsapify-router/angular-gsapify-router.js',
            './node_modules/hoshiImageLoader/dist/main.min.js',
            './node_modules/hoshiCustomContent/dist/main.min.js',
            './node_modules/headroom.js/dist/headroom.min.js',
            './node_modules/headroom.js/dist/angular.headroom.min.js'
        ]))
        .pipe(concat('vendor.js'))
        .pipe(gulpif(util.env.production, uglify()))
        .pipe(gulp.dest(dist.js))
        .pipe(jsFilter.restore)
        .pipe(cssFilter)
        .pipe(concat('vendor.css'))
        .pipe(gulpif(util.env.production, cssnano()))
        .pipe(gulp.dest(dist.css))
});
```

It's finding all of the main Bower files but none of my manual includes. Any idea why that would be?

Thanks for writing this lib!

**Comment by mauricedb** [comment]
@mcblum are you using gulp-main-bower-files  or main-bower-files itself. The require statements are missing from the code example but the syntax suggests you are using [main-bower-files](https://www.npmjs.com/package/main-bower-files) and not gulp-main-bower-files.

BTW I was not familiar with gulp-add-src but it doesn't look very promising to me.

![image](https://cloud.githubusercontent.com/assets/3197730/18791171/eb362c00-81b1-11e6-93ce-392aeb305b71.png)

**Comment by mcblum** [comment]
Ah crap, you're right.

` var mainBowerFiles = require('main-bower-files'); `

Would you suggest two separate vendor js files? I was hoping to grab everything from bower, do some manual includes, concat and minify.

**Comment by mauricedb** [comment]
Would need to look into this for a proper advice but at the very least you should be able to create to bundled files and then concatenate them into a single for download.

**Comment by mcblum** [comment]
Thank you @mauricedb! Have a great day.
