### ISSUE TITLE
Build Task does not reach all bower components

### ISSUE THREAD

**Issue by thekennysong** [mauricedb/gulp-main-bower-files#5]
gulp.task('build-bower', function(){
        return gulp.src('./bower.json')
           .pipe(plugins.mainBowerFiles())
          .pipe(gulp.dest('cleaned/bower_components'));
    });

In the cleaned/bower_components directory, not all the bower components from the original bower components folder (that are pulled in from bower.json file) are included.

**Comment by mauricedb** [comment]
@thekennysong Can you include the contents of your bower.json and the onserved as well as the expected result for me to investigate?

**Comment by thekennysong** [comment]
Below is the JSON:

{
  "name": "higi-web-portal",
  "description": "javascript dependencies",
  "main": "",
  "authors": [
    "Kenny Song <ksong@higi.com>"
  ],
  "license": "MIT",
  "homepage": "https://github.com/higish/higi-web-portal-2016",
  "moduleType": [
    "node"
  ],
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "moment": "~2.10.6",
    "fancybox": "~2.1.5",
    "highcharts": "~4.1.9",
    "slides": "~0.1.1",
    "jquery": "~2.1.4",
    "jquery-smooth-scroll": "~1.5.6",
    "scrollmagic": "~2.0.5",
    "jquery-ui": "~1.11.4",
    "jquery-throttle-debounce": "*",
    "jQuery.dotdotdot": "~1.7.4",
    "jquery.browser": "~0.0.8",
    "overscroll": "*",
    "jquery.stellar": "stellar.js#~0.6.2",
    "gsap": "~1.18.0",
    "jquery-unveil": "unveil#~1.3.0",
    "fuse.js": "~1.2.2",
    "js-cookie": "~2.0.3",
    "lightbox2": "lightbox#~2.8.1",
    "raphael": "~2.1.4",
    "ResponsiveSlides.js": "*"
  }
}


Here is the Gulpfile:


// Load Gulp
var gulp    = require('gulp'),
    plugins = require('gulp-load-plugins')();



// Start Watching: Run "gulp"
gulp.task('default', ['watch']);

// Minify Bower Components:
gulp.task('group-bower', function(){
    return gulp.src('bower.json')
        .pipe(plugins.mainBowerFiles())
        .pipe(gulp.dest('cleaned/bower_components'));
});

gulp.task('build-bower',function(){
    return gulp.src(['cleaned/bower_components/**/*.js',
        'cleaned/bower_components/**/**/*.js',
        'cleaned/bower_components/**/**/**/*.js'])
        .pipe(plugins.jshint())
        // .pipe(plugins.uglify())
        .pipe(plugins.concat('bower.scripts.min.js'))
        .pipe(gulp.dest('public/dist/js'))
        .pipe(plugins.livereload());
});

// Minify Custom JS: Run manually with: "gulp build-js"
gulp.task('build-js', function() {
  return gulp.src(['public/scripts/**/*.js',
    'public/scripts/**/**/*.js'])
    .pipe(plugins.jshint())
    .pipe(plugins.jshint.reporter('jshint-stylish'))
    .pipe(plugins.uglify())
    .pipe(plugins.concat('scripts.min.js'))
    .pipe(gulp.dest('public/dist/js'))
    .pipe(plugins.livereload());
});

// Minify Custom JS: Run manually with: "gulp build-js"
gulp.task('build-js-dependencies', function() {
  return gulp.src(['public/js-dependencies/**/*.js',
    'public/js-dependencies/**/**/*.js'])
    .pipe(plugins.jshint())
    .pipe(plugins.jshint.reporter('jshint-stylish'))
    .pipe(plugins.uglify())
    .pipe(plugins.concat('js-dependencies.min.js'))
    .pipe(gulp.dest('public/dist/js'))
    .pipe(plugins.livereload());
});


// SCSS to CSS: Run manually with: "gulp build-css"
gulp.task('build-css', function() {
    return gulp.src('public/css/*.scss')
        .pipe(plugins.plumber())
        .pipe(plugins.sass())
        .on('error', plugins.sass.logError)
        .pipe(plugins.autoprefixer(
            {
                browsers: [
                    '> 1%',
                    'last 2 versions',
                    'firefox >= 4',
                    'safari 7',
                    'safari 8',
                    'IE 8',
                    'IE 9',
                    'IE 10',
                    'IE 11'
                ],
                cascade: false
            }
        ))
        .pipe(plugins.cssmin())
        .pipe(gulp.dest('build')).on('error', plugins.sass.logError)
        .pipe(plugins.livereload());
});

// Default task
gulp.task('watch', function() {
    plugins.livereload.listen();
    gulp.watch('bower_components/**/**/*.js', ['group-bower']);
    gulp.watch(['bower_components/**/**/*.js','public/scripts/**/**/**/*.js'], ['build-bower']);
    gulp.watch(['public/js-dependencies/**/*.js','public/js-dependencies/**/**/*.js'], ['build-js-dependencies']);
    gulp.watch('public/scripts/**/*.js', ['build-js']);
    gulp.watch('public/css/*.scss', ['build-css']);
});

**Comment by mauricedb** [comment]
@thekennysong Taking a look at the used Bower packages I notice not all of them include a main file so gulp-main-bower-files doesn't know what to copy. In those cases where the main section is missing or wrong you can override it when calling gulp-main-bower-files. See also the Bootstrap example on the main page.

For example in your case FancyBox doesn't specify one or more main files. To fix that you can use the following Gulp task:

```
gulp.task('group-bower', function(){
	return gulp.src('bower.json')
		.pipe(plugins.mainBowerFiles({
			overrides:{
				fancybox: {
					main: './source/jquery.fancybox.js'
				}
			}
		}))
		.pipe(gulp.dest('cleaned/bower_components'));
});
```

This is not an issue in gulp-main-bower-files but the way the Bower packages where created. You will need to do the same for some of the other Gulp packages.
