### ISSUE TITLE
Concatenation issue on Windows with Gulp 4

### ISSUE THREAD

**Issue by adamfriedland** [mauricedb/gulp-main-bower-files#76]
`[Error] [11:18:13] 'build:Bower' errored after 861 ms[11:18:13] Error: Bower components directory does not exist at c:\project\SomePojectbower_components    at module.exports....`

After upgrading to the Gulp version 4 (using latest version of gulp-main-bower-files), I've encountered an issue where concatenation seems to have broken. I also tested this by creating a simple task such as 
```javascript
return gulp.src("./bower.json")
	.pipe(plugins.mainBowerFiles())
	.pipe(gulp.dest("./ui/lib"));
```
As mentioned in another post, I was able to fix this by changing the path in my `.bowerrc` from `"directory": "bower_components"` to `"directory": "\bower_components"` but this introduces problems for existing tools that relied on that pathing.

**Comment by mauricedb** [comment]
@adamfriedland Do you have a simple runnable demo of the issue to share so I can investigate? The reason I ask is that errors like this are often Bower package dependent.

**Comment by adamfriedland** [comment]
I just created a runnable demo showcasing the issue here:

https://github.com/adamfriedland/SimpleDemo

**Comment by mauricedb** [comment]
@adamfriedland Updating to 1.6.3 should fix your issue
